[project]
name = "expense-processing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Abhinav Gupta", email = "abhinavg9868@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "psycopg[binary]>=3.3.6",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.4",
]

[project.scripts]
expense-processing = "expense_processing:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
